### ISSUE TITLE
Report's generation is throwing 500's on the test server

### ISSUE THREAD

**Issue by iamkinetic** [CAUCA-9-1-1/survip-webapi#154]

**Comment by iamkinetic** [comment]
```
Oct 10 09:56:33 tests-server sshd[4979]: Connection closed by 10.10.255.38 port 42814 [preauth]
Oct 10 09:56:59 tests-server audit[4996]: ANOM_ABEND auid=4294967295 uid=101 gid=101 ses=4294967295 pid=4996 comm="wkhtmltopdf" exe="/usr/bin/wkhtmltopdf" sig=6
Oct 10 09:56:59 tests-server docker[11334]: fail: Microsoft.AspNetCore.Server.Kestrel[13]
Oct 10 09:56:59 tests-server docker[11334]:       Connection id "0HLHDV6Q0CP0N", Request id "0HLHDV6Q0CP0N:00000001": An unhandled exception was thrown by the application.
Oct 10 09:56:59 tests-server docker[11334]: System.Exception: Failed to generate PDF: Broken pipe ---> System.IO.IOException: Broken pipe
Oct 10 09:56:59 tests-server docker[11334]:    at System.IO.FileStream.WriteNative(ReadOnlySpan`1 source)
Oct 10 09:56:59 tests-server docker[11334]:    at System.IO.FileStream.WriteSpan(ReadOnlySpan`1 source)
Oct 10 09:56:59 tests-server docker[11334]:    at System.IO.FileStream.Write(Byte[] array, Int32 offset, Int32 count)
Oct 10 09:56:59 tests-server docker[11334]:    at WkWrap.HtmlToPdfConverter.InvokeWkHtmlToPdf(Stream input, Stream output, String settings, Nullable`1 executionTimeout)
Oct 10 09:56:59 tests-server docker[11334]:    at WkWrap.HtmlToPdfConverter.ConvertToPdfInternal(Stream input, Stream output, String settings, Nullable`1 executionTimeout)
Oct 10 09:56:59 tests-server docker[11334]:    --- End of inner exception stack trace ---
Oct 10 09:56:59 tests-server docker[11334]:    at WkWrap.HtmlToPdfConverter.ConvertToPdfInternal(Stream input, Stream output, String settings, Nullable`1 executionTimeout)
Oct 10 09:56:59 tests-server docker[11334]:    at Survi.Prevention.ServiceLayer.Services.ReportGenerationService.Generate(Guid inspectionId, Guid templateId, String languageCode) in /app/Survi.Prevention.ServiceLayer/Services/ReportGenerationService.cs:line 67
Oct 10 09:56:59 tests-server docker[11334]:    at Survi.Prevention.WebApi.Controllers.ReportGenerationController.Generate(Guid buildindId, Guid templateId, String languageCode) in /app/Survi.Prevention.WebApi/Controllers/ReportGenerationController .cs:line 20
Oct 10 09:56:59 tests-server docker[11334]:    at lambda_method(Closure , Object , Object[] )
Oct 10 09:56:59 tests-server docker[11334]:    at Microsoft.AspNetCore.Mvc.Internal.ActionMethodExecutor.SyncActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
Oct 10 09:56:59 tests-server docker[11334]:    at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeActionMethodAsync()
Oct 10 09:56:59 tests-server docker[11334]:    at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeNextActionFilterAsync()
Oct 10 09:56:59 tests-server docker[11334]:    at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow(ActionExecutedContext context)
Oct 10 09:56:59 tests-server docker[11334]:    at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
Oct 10 09:56:59 tests-server docker[11334]:    at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeInnerFilterAsync()
Oct 10 09:56:59 tests-server docker[11334]:    at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeNextResourceFilter()
Oct 10 09:56:59 tests-server docker[11334]:    at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResourceExecutedContext context)
Oct 10 09:56:59 tests-server docker[11334]:    at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
Oct 10 09:56:59 tests-server docker[11334]:    at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeFilterPipelineAsync()
Oct 10 09:56:59 tests-server docker[11334]:    at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeAsync()
Oct 10 09:56:59 tests-server docker[11334]:    at Microsoft.AspNetCore.Builder.RouterMiddleware.Invoke(HttpContext httpContext)
Oct 10 09:56:59 tests-server docker[11334]:    at Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware.Invoke(HttpContext context)
Oct 10 09:56:59 tests-server docker[11334]:    at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIIndexMiddleware.Invoke(HttpContext httpContext)
Oct 10 09:56:59 tests-server docker[11334]:    at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext)
Oct 10 09:56:59 tests-server docker[11334]:    at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
Oct 10 09:56:59 tests-server docker[11334]:    at Microsoft.AspNetCore.Cors.Infrastructure.CorsMiddleware.Invoke(HttpContext context)
Oct 10 09:56:59 tests-server docker[11334]:    at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProcessRequests[TContext](IHttpApplication`1 application)
```

**Comment by iamkinetic** [comment]
WkWrap doesn't seem to be maintained anymore, or at least, the github page doesn't exist anymore.

**Comment by iamkinetic** [comment]
Alternative: 
* JsReport:  https://stackoverflow.com/a/45840308/6347013
* DinkToPdf : https://github.com/rdvojmoc/DinkToPdf  (https://jsreport.net/learn/dotnet)
