### ISSUE TITLE
Crash in the API when adding new Niveau de risque par SSI

### ISSUE THREAD

**Issue by Zalverick** [CAUCA-9-1-1/survip-webapi#256]
**Describe the bug**
When I try to add "Niveau de risques par SSI" for CAUCA SSI, I get this exception in the API and the changes are not saved:

System.InvalidOperationException
  HResult=0x80131509
  Message=The entity type 'List<FireSafetyDepartmentInspectionConfigurationRiskLevel>' was not found. Ensure that the entity type has been added to the model.
  Source=Microsoft.EntityFrameworkCore
  StackTrace:
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.GetOrCreateEntry(Object entity)
   at Microsoft.EntityFrameworkCore.DbContext.RemoveRange(IEnumerable`1 entities)
   at Microsoft.EntityFrameworkCore.DbContext.RemoveRange(Object[] entities)
   at Survi.Prevention.ServiceLayer.Services.FireSafetyDepartmentInspectionConfigurationService.UpdateRiskLevels(FireSafetyDepartmentInspectionConfigurationForEdition entity, FireSafetyDepartmentInspectionConfiguration currentConfig) in C:\Dev\SURVI-Prevention\survip-webapi\Survi.Prevention.ServiceLayer\Services\FireSafetyDepartmentInspectionConfigurationService.cs:line 139
   at Survi.Prevention.ServiceLayer.Services.FireSafetyDepartmentInspectionConfigurationService.PushDtoToEntity(FireSafetyDepartmentInspectionConfigurationForEdition entity, FireSafetyDepartmentInspectionConfiguration currentConfig) in C:\Dev\SURVI-Prevention\survip-webapi\Survi.Prevention.ServiceLayer\Services\FireSafetyDepartmentInspectionConfigurationService.cs:line 130
   at Survi.Prevention.ServiceLayer.Services.FireSafetyDepartmentInspectionConfigurationService.AddOrUpdate(FireSafetyDepartmentInspectionConfigurationForEdition entity) in C:\Dev\SURVI-Prevention\survip-webapi\Survi.Prevention.ServiceLayer\Services\FireSafetyDepartmentInspectionConfigurationService.cs:line 109
   at Survi.Prevention.WebApi.Controllers.FireSafetyDepartmentRiskLevelController.Post(FireSafetyDepartmentInspectionConfigurationForEdition entity) in C:\Dev\SURVI-Prevention\survip-webapi\Survi.Prevention.WebApi\Controllers\FireSafetyDepartmentRiskLevelController.cs:line 52
   at Microsoft.Extensions.Internal.ObjectMethodExecutor.Execute(Object target, Object[] parameters)
   at Microsoft.AspNetCore.Mvc.Internal.ActionMethodExecutor.SyncActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeActionMethodAsync>d__12.MoveNext()

**To Reproduce**
1. Log in with a user that has access to CAUCA SSI.
2. Go to the SSI management section
3. Click "Niveau de risque par SSI"
4. Add a new line 
5. Select CAUCA SSI
6. Check a few Niveau de Risques
7 Click SAVE.

**Expected behavior**
Should not crash and save the changes.

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by iamkinetic** [comment]
Fix in #301.
